name: CD

on:
  release:
    types:
      - published

jobs:
  merge-dev-to-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure Git User
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch Dev and Main Branches
      run: |
        git fetch origin dev
        git fetch origin main

    - name: Checkout Main Branch
      run: |
        git checkout -b main origin/main || git checkout main

    - name: Merge Dev into Main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_TITLE="${{ github.event.release.name }}"
        if [ -z "$RELEASE_TITLE" ]; then
          RELEASE_TITLE="Release ${{ github.event.release.tag_name }}"
        fi

        # 最新のリモート変更を取り込み
        git pull origin main

        # dev を main にマージ（コンフリクト発生時は自動解決）
        git merge origin/dev --allow-unrelated-histories -m "Merge dev into main - $RELEASE_TITLE" || true

        # コンフリクト解消: dev の変更を優先
        if git diff --name-only --diff-filter=U | grep -q '^'; then
          echo "Conflicts detected. Resolving by prioritizing 'dev'."
          git merge --abort
          git reset --hard origin/dev
          git add .
          git commit -m "Resolve conflicts by prioritizing dev branch - $RELEASE_TITLE"
        fi

        # リモートにプッシュ（非強制で試行）
        git push origin main || true

        # 必要に応じて強制プッシュ
        if git log origin/main..main | grep -q '^'; then
          echo "Force pushing due to diverging histories."
          git push origin main --force-with-lease
        fi
