name: CD

on:
  release:
    types:
      - published

jobs:
  merge-dev-to-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure Git User
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch Dev and Main Branches
      run: |
        git fetch origin dev
        git fetch origin main

    - name: Checkout Main Branch
      run: |
        git checkout -b main origin/main

    - name: Merge Dev into Main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_TITLE="${{ github.event.release.name }}"
        if [ -z "$RELEASE_TITLE" ]; then
          RELEASE_TITLE="Release ${{ github.event.release.tag_name }}"
        fi
        git merge origin/dev --allow-unrelated-histories -m "Merge dev into main - $RELEASE_TITLE" || true
        # コンフリクトを自動解決
        git merge --abort || true
        git reset --hard origin/dev
        git push origin main
